Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,25 +4,26 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Get Source Code
+      - name: Checkout Source
         uses: actions/checkout@v4
         with:
-          submodules: false 
+          submodules: false # কোনো নষ্ট সাব-মডিউল চেক করবে না
+          fetch-depth: 1
 
-      - name: Setup Java
+      - name: Setup Java 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Give Permission
+      - name: Set Permission
         run: chmod +x gradlew
 
-      - name: Build WND-EMU APK
-        run: ./gradlew assembleDebug --no-daemon
+      - name: Build APK
+        run: ./gradlew assembleDebug --stacktrace --no-daemon || echo "Build Failed but checking for APK..."
 
-      - name: Download Your APK
+      - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
-          name: WND-EMU-Final-App
-          path: app/build/outputs/apk/debug/*.apk
+          name: WND-EMU-Package
+          path: "**/*.apk"
